include_directories(Sources)
set(TOOLS_SRC
        Sources/Debug/Debug.cpp
        Sources/Debug/Debug.hpp
        Sources/Exceptions/MyException.cpp
        Sources/Exceptions/MyException.hpp
        Sources/Queue/WriteOnlyQueue.hpp
        Sources/Queue/QueueImplem.cpp
        Sources/Queue/QueueImplem.hpp)

set(SRC
        ${TOOLS_SRC}
        Sources/ECsPressPapp.cpp
        Sources/ECsPressPapp.hpp
        Sources/Network/HTTP.cpp
        Sources/Network/HTTP.hpp
        Sources/Network/INetwork.hpp
        Sources/Network/HttpRequest.cpp
        Sources/Network/HttpRequest.hpp
        Sources/Network/HttpResponse.cpp
        Sources/Network/HttpResponse.hpp
)
