name: Build and Test
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build-ubuntu:
    name: Build project
    runs-on: ubuntu-latest
    container:
      image: "gcc:12.3.0"
    env:
      TARGET_NAME: express-cpp
      BUILD_TYPE: Release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build project
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          cmake --build build --target ${{ env.TARGET_NAME }} -j
  build-windows:
    name: Build project
    runs-on: windows-latest
    env:
      TARGET_NAME: express-cpp
      BUILD_TYPE: Release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build project
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          cmake --build build --target ${{ env.TARGET_NAME }} -j
