name: Build and Test
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build-ubuntu:
    name: Build project (ubuntu)
    runs-on: ubuntu-latest
    container:
      image: "antwxne/cmake:3.28.1"
    env:
      TARGET_NAME: express-cpp
      BUILD_TYPE: Release
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          cmake --build build --target ${{ env.TARGET_NAME }} -j
#  build-windows:
#    name: Build project (Windows)
#    runs-on: windows-latest
#    env:
#      TARGET_NAME: express-cpp
#      BUILD_TYPE: Release
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: recursive
#      - name: Build project
#        run: |
#          cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
#          cmake --build build --target ${{ env.TARGET_NAME }} -j
