name: Build and Test
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build-ubuntu:
    name: Build project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            VCPKG_BOOTSTRAP_CMD: vcpkg\bootstrap-vcpkg.bat
          - os: ubuntu-latest
            VCPKG_BOOTSTRAP_CMD: vcpkg/bootstrap-vcpkg.sh
    env:
      CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install VCPKG
        run: |
          git clone https://github.com/Microsoft/vcpkg.git ${{ github.workspace }}/vcpkg
          ${{ github.workspace }}/${{ matrix.VCPKG_BOOTSTRAP_CMD }}
      - name: Build project
        run: |
          cmake -B build
          cmake --build build
